#This file sets usr_path.mk variables to cmake variables that can later be used in CMakeLists.txt
set(WORKSPACE_DIR $ENV{WORKSPACE_DIR})
set(BUILD_DIR $ENV{BUILD_DIR})

set(SEARCH_ENGINE_DIR $ENV{SEARCH_ENGINE_DIR})

set(ENGINE_DIR $ENV{ENGINE_DIR})
set(ENGINE_SRC_DIR $ENV{ENGINE_SRC_DIR})
set(ENGINE_INC_DIR $ENV{ENGINE_INC_DIR})

set(WORDS_LIST_DIR $ENV{WORDS_LIST_DIR})
set(WORDS_LIST_SRC_DIR $ENV{WORDS_LIST_SRC_DIR})
set(WORDS_LIST_INC_DIR $ENV{WORDS_LIST_INC_DIR})

set(TOOLS_DIR $ENV{TOOLS_DIR})
set(TOOLS_SRC_DIR $ENV{TOOLS_SRC_DIR})
set(TOOLS_INC_DIR $ENV{TOOLS_INC_DIR})

set(USR_FCT_DIR $ENV{USR_FCT_DIR})
set(USR_FCT_SRC_DIR $ENV{USR_FCT_SRC_DIR})
set(USR_FCT_INC_DIR $ENV{USR_FCT_INC_DIR})

set(TESTS_DIR $ENV{TESTS_DIR})
set(BUILD_TESTS_DIR $ENV{BUILD_TESTS_DIR})
set(UNIT_TESTS_DIR $ENV{UNIT_TESTS_DIR})
set(INTEGRATION_TESTS_DIR $ENV{INTEGRATION_TESTS_DIR})
set(BUILD_UNIT_TESTS_DIR $ENV{BUILD_UNIT_TESTS_DIR})
set(BUILD_INTEGRATION_TESTS_DIR $ENV{BUILD_INTEGRATION_TESTS_DIR})

set(RUN_MODE $ENV{RUN_MODE})